# Config file for [Air](https://github.com/cosmtrek/air) in TOML format

# Working directory
# . or absolute path, please note that the directories following must be under root
root = "." 
tmp_dir = "build"

[build]
cmd = "make dev-build"
# Binary file yields from `cmd`.
bin = "build/dev"

# Customize binary.
full_bin = "make dev-run"
# This log file places in your tmp_dir.
log = "air_errors.log"
# Watch these filename extensions.
include_ext = ["go", "graphql"]
# Ignore these filename extensions or directories.
exclude_dir = ["tmp", "build"]
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000 # ms
# Stop running old binary when build errors occur.
stop_on_error = true

[log]
# Show log time
time = true

[misc]
# Delete tmp directory on exit
clean_on_exit = true