version: "3.8"
services:
  db:
    image: postgres
    container_name: "spoonfed-go-dev-db"
    env_file:
      - pg.env
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  dev:
    working_dir: /spoonfed-go
    container_name: "spoonfed-go-dev"
    build:
      context: .
      dockerfile: docker/dev.dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - .:/spoonfed-go
    depends_on: 
      - db
  prod:
    working_dir: /spoonfed-go
    container_name: "spoonfed-go"
    build:
      context: .
      dockerfile: docker/prod.dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
volumes: 
  pgdata:
