version: "3.8"
services:
  dev:
    working_dir: /spoonfed-go
    container_name: "spoonfed-go-dev"
    build:
      context: .
      dockerfile: docker/dev.dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
    volumes:
      - .:/spoonfed-go
  prod:
    working_dir: /spoonfed-go
    container_name: "spoonfed-go"
    build:
      context: .
      dockerfile: docker/prod.dockerfile
    env_file:
      - .env
    ports:
      - 8080:8080
