// Code generated by github.com/vektah/dataloaden, DO NOT EDIT.

package dataloader

import (
	"sync"
	"time"
)

// RecipeLikeLoaderConfig captures the config to create a new RecipeLikeLoader
type RecipeLikeLoaderConfig struct {
	// Fetch is a method that provides the data for the loader
	Fetch func(ids []string) ([]*int64, []error)

	// Wait is how long wait before sending a batch
	Wait time.Duration

	// MaxBatch will limit the maximum number of ids to send in one batch, 0 = not limit
	MaxBatch int
}

// NewRecipeLikeLoader creates a new RecipeLikeLoader given a fetch, wait, and maxBatch
func NewRecipeLikeLoader(config RecipeLikeLoaderConfig) *RecipeLikeLoader {
	return &RecipeLikeLoader{
		fetch:    config.Fetch,
		wait:     config.Wait,
		maxBatch: config.MaxBatch,
	}
}

// RecipeLikeLoader batches and caches requests
type RecipeLikeLoader struct {
	// this method provides the data for the loader
	fetch func(ids []string) ([]*int64, []error)

	// how long to done before sending a batch
	wait time.Duration

	// this will limit the maximum number of ids to send in one batch, 0 = no limit
	maxBatch int

	// INTERNAL

	// lazily created cache
	cache map[string]*int64

	// the current batch. ids will continue to be collected until timeout is hit,
	// then everything will be sent to the fetch method and out to the listeners
	batch *recipeLikeLoaderBatch

	// mutex to prevent races
	mu sync.Mutex
}

type recipeLikeLoaderBatch struct {
	ids     []string
	data    []*int64
	error   []error
	closing bool
	done    chan struct{}
}

// Load a Like by key, batching and caching will be applied automatically
func (l *RecipeLikeLoader) Load(key string) (*int64, error) {
	return l.LoadThunk(key)()
}

// LoadThunk returns a function that when called will block waiting for a Like.
// This method should be used if you want one goroutine to make requests to many
// different data loaders without blocking until the thunk is called.
func (l *RecipeLikeLoader) LoadThunk(key string) func() (*int64, error) {
	l.mu.Lock()
	if it, ok := l.cache[key]; ok {
		l.mu.Unlock()
		return func() (*int64, error) {
			return it, nil
		}
	}
	if l.batch == nil {
		l.batch = &recipeLikeLoaderBatch{done: make(chan struct{})}
	}
	batch := l.batch
	pos := batch.keyIndex(l, key)
	l.mu.Unlock()

	return func() (*int64, error) {
		<-batch.done

		var data *int64
		if pos < len(batch.data) {
			data = batch.data[pos]
		}

		var err error
		// its convenient to be able to return a single error for everything
		if len(batch.error) == 1 {
			err = batch.error[0]
		} else if batch.error != nil {
			err = batch.error[pos]
		}

		if err == nil {
			l.mu.Lock()
			l.unsafeSet(key, data)
			l.mu.Unlock()
		}

		return data, err
	}
}

// LoadAll fetches many ids at once. It will be broken into appropriate sized
// sub batches depending on how the loader is configured
func (l *RecipeLikeLoader) LoadAll(ids []string) ([]*int64, []error) {
	results := make([]func() (*int64, error), len(ids))

	for i, key := range ids {
		results[i] = l.LoadThunk(key)
	}

	likes := make([]*int64, len(ids))
	errors := make([]error, len(ids))
	for i, thunk := range results {
		likes[i], errors[i] = thunk()
	}
	return likes, errors
}

// LoadAllThunk returns a function that when called will block waiting for a Likes.
// This method should be used if you want one goroutine to make requests to many
// different data loaders without blocking until the thunk is called.
func (l *RecipeLikeLoader) LoadAllThunk(ids []string) func() ([]*int64, []error) {
	results := make([]func() (*int64, error), len(ids))
	for i, key := range ids {
		results[i] = l.LoadThunk(key)
	}
	return func() ([]*int64, []error) {
		likes := make([]*int64, len(ids))
		errors := make([]error, len(ids))
		for i, thunk := range results {
			likes[i], errors[i] = thunk()
		}
		return likes, errors
	}
}

// Prime the cache with the provided key and value. If the key already exists, no change is made
// and false is returned.
// (To forcefully prime the cache, clear the key first with loader.clear(key).prime(key, value).)
func (l *RecipeLikeLoader) Prime(key string, value *int64) bool {
	l.mu.Lock()
	var found bool
	if _, found = l.cache[key]; !found {
		l.unsafeSet(key, value)
	}
	l.mu.Unlock()
	return !found
}

// Clear the value at key from the cache, if it exists
func (l *RecipeLikeLoader) Clear(key string) {
	l.mu.Lock()
	delete(l.cache, key)
	l.mu.Unlock()
}

func (l *RecipeLikeLoader) unsafeSet(key string, value *int64) {
	if l.cache == nil {
		l.cache = map[string]*int64{}
	}
	l.cache[key] = value
}

// keyIndex will return the location of the key in the batch, if its not found
// it will add the key to the batch
func (b *recipeLikeLoaderBatch) keyIndex(l *RecipeLikeLoader, key string) int {
	for i, existingKey := range b.ids {
		if key == existingKey {
			return i
		}
	}

	pos := len(b.ids)
	b.ids = append(b.ids, key)
	if pos == 0 {
		go b.startTimer(l)
	}

	if l.maxBatch != 0 && pos >= l.maxBatch-1 {
		if !b.closing {
			b.closing = true
			l.batch = nil
			go b.end(l)
		}
	}

	return pos
}

func (b *recipeLikeLoaderBatch) startTimer(l *RecipeLikeLoader) {
	time.Sleep(l.wait)
	l.mu.Lock()

	// we must have hit a batch limit and are already finalizing this batch
	if b.closing {
		l.mu.Unlock()
		return
	}

	l.batch = nil
	l.mu.Unlock()

	b.end(l)
}

func (b *recipeLikeLoaderBatch) end(l *RecipeLikeLoader) {
	b.data, b.error = l.fetch(b.ids)
	close(b.done)
}
