// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type IDFilterInput struct {
	Is     *string   `json:"is"`
	NotIs  *string   `json:"notIs"`
	Has    []*string `json:"has"`
	NotHas []*string `json:"notHas"`
}

type Image struct {
	URL  string `json:"url"`
	Name string `json:"name"`
}

type IntFilterInput struct {
	Equals      *int `json:"equals"`
	LessThan    *int `json:"lessThan"`
	GreaterThan *int `json:"greaterThan"`
}

type PageInfo struct {
	Cursor      string `json:"cursor"`
	HasNextPage bool   `json:"hasNextPage"`
}

type RecipeConnection struct {
	Edges    []*RecipeEdge `json:"edges"`
	PageInfo *PageInfo     `json:"pageInfo"`
}

type RecipeEdge struct {
	Cursor string  `json:"cursor"`
	Node   *Recipe `json:"node"`
}

type RecipeTimeType struct {
	Prep     *string `json:"prep"`
	Cook     *string `json:"cook"`
	Ready    *string `json:"ready"`
	Active   *string `json:"active"`
	Inactive *string `json:"inactive"`
	Total    string  `json:"total"`
}

type StringFilterInput struct {
	Contains *string `json:"contains"`
}
