// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type EditRecipeInput struct {
	ID           string           `json:"ID"`
	Name         *string          `json:"name"`
	Servings     *string          `json:"servings"`
	Images       []*ImageInput    `json:"images"`
	Time         *RecipeTimeInput `json:"time"`
	Ingredients  []string         `json:"ingredients"`
	Instructions []string         `json:"instructions"`
}

type PageInfo struct {
	Cursor      string `json:"cursor"`
	HasNextPage bool   `json:"hasNextPage"`
}

type RecipeConnection struct {
	Edges    []*RecipeEdge `json:"edges"`
	PageInfo *PageInfo     `json:"pageInfo"`
}

type RecipeEdge struct {
	Cursor string  `json:"cursor"`
	Node   *Recipe `json:"node"`
}

type RecipeTimeInput struct {
	Prep     *string `json:"prep"`
	Cook     *string `json:"cook"`
	Ready    *string `json:"ready"`
	Total    string  `json:"total"`
	Active   *string `json:"active"`
	Inactive *string `json:"inactive"`
}

type SortInput struct {
	Key   string    `json:"key"`
	Order SortOrder `json:"order"`
}

type UserName struct {
	First *string `json:"first"`
	Last  *string `json:"last"`
	Full  *string `json:"full"`
}
